export const types = Object.freeze({
    // Async
    FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
    LIKE_POST_ASYNC: 'LIKE_POST_ASYNC',
    UNLIKE_POST_ASYNC: 'UNLIKE_POST_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',

    // Sync
    FILL_POSTS: 'FILL_POSTS',
    LIKE_POST: 'LIKE_POST',
    UNLIKE_POST: 'UNLIKE_POST',
    CREATE_POST: 'CREATE_POST',
    REMOVE_POST: 'REMOVE_POST'
});
