export const types = Object.freeze({
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',

    SET_ONLINE_STATE: 'SET_ONLINE_STATE',
    SET_OFFLINE_STATE: 'SET_OFFLINE_STATE',
});
